services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /:/srv
      - ./database:/database
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`example.domain.dev`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser.middlewares=tinyauth"

networks:
  traefik_proxy:
    external: true
