global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

metrics:
  prometheus: true

api:
  dashboard: true
  insecure: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'email@example.com'
      storage: /letsencrypt/acme.json
      caserver: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      httpChallenge:
        entryPoint: web
      dnsChallenge:
        provider: ovh
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

accesslog: true
